<a class="text-secondary text-decoration-none" href="<?=$admin?'/'.h($location).'/admin?sig='.rawurlencode($sig):'/'.h($location)?>">← Zurück</a>
<h1 class="h3 mt-3 mb-1"><?=sprintf('%02d. Dezember (%s)', $day, $app->weekdayShort($day))?></h1><p class="text-secondary mb-4"><?=h($locationName)?></p>
<?php if($errors):?><div class="alert alert-danger">Bitte prüfen Sie die markierten Felder.</div><?php endif?>
<form method="post" novalidate><input type="hidden" name="_csrf" value="<?=h($app->csrf())?>"><?php if($admin):?><input type="hidden" name="sig" value="<?=h($sig)?>"><?php endif?>
<?php if($admin):?><div class="mb-3"><label class="form-label required" for="day">Tag</label><select class="form-select <?=isset($errors['day'])?'is-invalid':''?>" id="day" name="day" required><?php foreach(range(1,23) as $availableDay): $isAvailable=in_array($availableDay,$availableDays,true)||$availableDay===$day?><option value="<?=$availableDay?>" <?=$availableDay===$day?'selected':''?><?=!$isAvailable?' disabled':''?>><?=sprintf('%02d. Dezember',$availableDay)?></option><?php endforeach?></select><?php if(isset($errors['day'])):?><div class="invalid-feedback"><?=h($errors['day'])?></div><?php endif?></div><?php endif?>
<div class="mb-3"><label class="form-label required" for="name">Name</label><input class="form-control <?=isset($errors['name'])?'is-invalid':''?>" id="name" name="name" value="<?=h($data['name'])?>" required><?php if(isset($errors['name'])):?><div class="invalid-feedback"><?=h($errors['name'])?></div><?php endif?></div>
<div class="mb-3"><label class="form-label required" for="address">Ortsangabe</label><input class="form-control <?=isset($errors['address'])?'is-invalid':''?>" id="address" name="address" value="<?=h($data['address'])?>" placeholder="z.B. Buchenstr. 29" required><?php if(isset($errors['address'])):?><div class="invalid-feedback"><?=h($errors['address'])?></div><?php endif?></div>
<div class="mb-3 mt-3"><label class="form-label required" for="phone">Telefon</label><input class="form-control <?=isset($errors['phone'])?'is-invalid':''?>" id="phone" name="phone" type="tel" value="<?=h($data['phone'])?>" required></div>
<div class="mb-3"><label class="form-label" for="email">E-Mail <span class="text-secondary">(optional; wenn vorhanden bitte angeben)</span></label><input class="form-control <?=isset($errors['email'])?'is-invalid':''?>" id="email" name="email" type="email" value="<?=h($data['email'])?>"><?php if(isset($errors['email'])):?><div class="invalid-feedback"><?=h($errors['email'])?></div><?php endif?></div>
<div class="form-check mb-4"><input class="form-check-input <?=isset($errors['publication_consent'])?'is-invalid':''?>" type="checkbox" value="1" id="publication_consent" name="publication_consent" <?=!empty($data['publication_consent'])?'checked':''?> required><label class="form-check-label" for="publication_consent">Ich bin damit einverstanden, dass mein Name und die angegebene Adresse als Veranstaltungsort des Lebendigen Adventskalenders öffentlich auf der Homepage veröffentlicht werden.</label><?php if(isset($errors['publication_consent'])):?><div class="invalid-feedback"><?=h($errors['publication_consent'])?></div><?php endif?></div>
<button class="btn btn-success btn-lg w-100" id="save-button" type="submit"<?=empty($data['publication_consent'])?' disabled':''?>><?=$admin?'Speichern':'Verbindlich anmelden'?></button></form>
<script>document.addEventListener('DOMContentLoaded',function(){const consent=document.getElementById('publication_consent');const button=document.getElementById('save-button');if(!consent||!button){return;}const update=function(){button.disabled=!consent.checked;};consent.addEventListener('change',update);update();});</script>
