<a class="text-secondary text-decoration-none" href="<?=$admin?'/'.h($location).'/admin?sig='.rawurlencode($sig):'/'.h($location)?>">← Zurück</a>
<h1 class="h3 mt-3 mb-1"><?=sprintf('%02d. Dezember (%s)', $day, $app->weekdayShort($day))?></h1><p class="text-secondary mb-4"><?=h($locationName)?></p>
<?php if($errors):?><div class="alert alert-danger">Bitte prüfen Sie die markierten Felder.</div><?php endif?>
<form method="post" novalidate><input type="hidden" name="_csrf" value="<?=h($app->csrf())?>"><?php if($admin):?><input type="hidden" name="sig" value="<?=h($sig)?>"><?php endif?>
<?php if($admin):?><div class="mb-3"><label class="form-label required" for="day">Tag</label><select class="form-select <?=isset($errors['day'])?'is-invalid':''?>" id="day" name="day" required><?php foreach(range(1,23) as $availableDay): $isAvailable=in_array($availableDay,$availableDays,true)||$availableDay===$day?><option value="<?=$availableDay?>" <?=$availableDay===$day?'selected':''?><?=!$isAvailable?' disabled':''?>><?=sprintf('%02d. Dezember',$availableDay)?></option><?php endforeach?></select><?php if(isset($errors['day'])):?><div class="invalid-feedback"><?=h($errors['day'])?></div><?php endif?></div><?php endif?>
<div class="mb-3"><label class="form-label required" for="name">Name</label><input class="form-control <?=isset($errors['name'])?'is-invalid':''?>" id="name" name="name" value="<?=h($data['name'])?>" required><?php if(isset($errors['name'])):?><div class="invalid-feedback"><?=h($errors['name'])?></div><?php endif?></div>
<div class="row g-2"><div class="col"><label class="form-label required" for="street">Straße</label><input class="form-control <?=isset($errors['street'])?'is-invalid':''?>" id="street" name="street" value="<?=h($data['street'])?>" placeholder="z.B. Buchenstraße" required><?php if(isset($errors['street'])):?><div class="invalid-feedback"><?=h($errors['street'])?></div><?php endif?></div>
<div class="col-4 col-sm-3"><label class="form-label required" for="house_number">Hausnummer</label><input class="form-control <?=isset($errors['house_number'])?'is-invalid':''?>" id="house_number" name="house_number" value="<?=h($data['house_number'])?>" placeholder="z.B. 29" required><?php if(isset($errors['house_number'])):?><div class="invalid-feedback"><?=h($errors['house_number'])?></div><?php endif?></div></div>
<div class="mb-3 mt-3"><label class="form-label required" for="phone">Telefon</label><input class="form-control <?=isset($errors['phone'])?'is-invalid':''?>" id="phone" name="phone" type="tel" value="<?=h($data['phone'])?>" required><?php if(isset($errors['phone'])):?><div class="invalid-feedback"><?=h($errors['phone'])?></div><?php endif?></div>
<div class="mb-3"><label class="form-label" for="email">E-Mailadresse <span class="text-secondary">(falls vorhanden)</span></label><input class="form-control <?=isset($errors['email'])?'is-invalid':''?>" id="email" name="email" type="email" value="<?=h($data['email'])?>"><?php if(isset($errors['email'])):?><div class="invalid-feedback"><?=h($errors['email'])?></div><?php endif?></div>
<div class="form-check mb-4"><input class="form-check-input <?=isset($errors['publication_consent'])?'is-invalid':''?>" type="checkbox" value="1" id="publication_consent" name="publication_consent" <?=!empty($data['publication_consent'])?'checked':''?> required><label class="form-check-label" for="publication_consent"><?=h($app->publicationConsentText())?></label><?php if(isset($errors['publication_consent'])):?><div class="invalid-feedback"><?=h($errors['publication_consent'])?></div><?php endif?></div>
<button class="btn btn-success btn-lg w-100" id="save-button" type="submit"<?=empty($data['publication_consent'])?' disabled':''?>><?=$admin?'Speichern':'Verbindlich anmelden'?></button></form>
<script>document.addEventListener('DOMContentLoaded',function(){const consent=document.getElementById('publication_consent');const button=document.getElementById('save-button');if(!consent||!button){return;}const update=function(){button.disabled=!consent.checked;};consent.addEventListener('change',update);update();});</script>
