<a class="text-secondary text-decoration-none" href="<?=$admin?'/'.h($location).'/admin?sig='.rawurlencode($sig):'/'.h($location)?>">← Zurück</a>
<h1 class="h3 mt-3 mb-1"><?=sprintf('%02d. Dezember', $day)?></h1><p class="text-secondary mb-4"><?=h($locationName)?></p>
<?php if($errors):?><div class="alert alert-danger">Bitte prüfen Sie die markierten Felder.</div><?php endif?>
<form method="post" novalidate><input type="hidden" name="_csrf" value="<?=h($app->csrf())?>"><?php if($admin):?><input type="hidden" name="sig" value="<?=h($sig)?>"><?php endif?>
<div class="mb-3"><label class="form-label required" for="name">Name</label><input class="form-control <?=isset($errors['name'])?'is-invalid':''?>" id="name" name="name" value="<?=h($data['name'])?>" required><?php if(isset($errors['name'])):?><div class="invalid-feedback"><?=h($errors['name'])?></div><?php endif?></div>
<div class="row g-3"><div class="col-8"><label class="form-label required" for="street">Straße</label><input class="form-control <?=isset($errors['street'])?'is-invalid':''?>" id="street" name="street" value="<?=h($data['street'])?>" required></div><div class="col-4"><label class="form-label required" for="house_number">Hausnr.</label><input class="form-control <?=isset($errors['house_number'])?'is-invalid':''?>" id="house_number" name="house_number" value="<?=h($data['house_number'])?>" required></div></div>
<div class="mb-3 mt-3"><label class="form-label required" for="phone">Telefon</label><input class="form-control <?=isset($errors['phone'])?'is-invalid':''?>" id="phone" name="phone" type="tel" value="<?=h($data['phone'])?>" required></div>
<div class="mb-3"><label class="form-label" for="email">E-Mail <span class="text-secondary">(optional)</span></label><input class="form-control <?=isset($errors['email'])?'is-invalid':''?>" id="email" name="email" type="email" value="<?=h($data['email'])?>"><?php if(isset($errors['email'])):?><div class="invalid-feedback"><?=h($errors['email'])?></div><?php endif?></div>
<div class="form-check mb-4"><input class="form-check-input <?=isset($errors['publication_consent'])?'is-invalid':''?>" type="checkbox" value="1" id="publication_consent" name="publication_consent" <?=!empty($data['publication_consent'])?'checked':''?>><label class="form-check-label" for="publication_consent">Ich bin damit einverstanden, dass mein Name und die angegebene Adresse als Veranstaltungsort des Lebendigen Adventskalenders öffentlich auf der Homepage veröffentlicht werden.</label><?php if(isset($errors['publication_consent'])):?><div class="invalid-feedback"><?=h($errors['publication_consent'])?></div><?php endif?></div>
<button class="btn btn-success btn-lg w-100" type="submit"><?=$admin?'Speichern':'Verbindlich anmelden'?></button></form>
